name: deploy react part
on: [push]

defaults:
  run:
    working-directory: lab03

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: go into react folder
        # run: cd lab03
      # - name: Install dependencies
        # run: npm ci
      - name: Build
        run: npm run deploy
